[2025-04-02T06:23:00.822+0000] {processor.py:186} INFO - Started process (PID=683) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:00.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:23:00.828+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:00.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:00.848+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:00.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseOperator.__init__() missing 1 required positional argument: 'task_id'
[2025-04-02T06:23:00.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:00.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.074 seconds
[2025-04-02T06:23:02.848+0000] {processor.py:186} INFO - Started process (PID=690) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:02.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:23:02.851+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:02.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:02.858+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:02.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseOperator.__init__() missing 1 required positional argument: 'task_id'
[2025-04-02T06:23:02.859+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:02.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2025-04-02T06:23:33.505+0000] {processor.py:186} INFO - Started process (PID=754) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:33.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:23:33.513+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:33.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:33.524+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:33.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseOperator.__init__() missing 1 required positional argument: 'task_id'
[2025-04-02T06:23:33.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:33.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2025-04-02T06:23:51.278+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:51.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:23:51.283+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:51.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:51.293+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:51.291+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Task 1' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:23:51.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:51.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2025-04-02T06:23:57.347+0000] {processor.py:186} INFO - Started process (PID=813) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:57.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:23:57.351+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:57.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:57.362+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:23:57.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Task 1' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:23:57.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:23:57.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2025-04-02T06:24:00.404+0000] {processor.py:186} INFO - Started process (PID=814) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:00.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:24:00.407+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:24:00.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:00.415+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:24:00.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Task 1' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:24:00.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:00.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2025-04-02T06:24:30.937+0000] {processor.py:186} INFO - Started process (PID=878) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:30.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:24:30.943+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:24:30.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:30.952+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:24:30.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Task 1' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:24:30.953+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:30.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2025-04-02T06:24:40.939+0000] {processor.py:186} INFO - Started process (PID=906) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:40.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:24:40.945+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:24:40.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:40.961+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:24:40.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Task 1' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:24:40.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:24:40.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2025-04-02T06:25:09.273+0000] {processor.py:186} INFO - Started process (PID=970) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:09.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:25:09.275+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:09.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:09.289+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:09.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 25, in <module>
    task_1 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'task 1' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:25:09.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:09.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2025-04-02T06:25:11.356+0000] {processor.py:186} INFO - Started process (PID=971) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:11.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:25:11.359+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:11.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:11.367+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:11.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 29, in <module>
    task_2 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Task 2' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:25:11.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:11.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2025-04-02T06:25:13.407+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:13.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:25:13.409+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:13.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:13.416+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:13.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 33, in <module>
    task_3 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Task 3' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:25:13.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:13.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2025-04-02T06:25:14.435+0000] {processor.py:186} INFO - Started process (PID=973) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:14.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:25:14.440+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:14.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:14.454+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:14.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 33, in <module>
    task_3 = EmptyOperator(
             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 976, in __init__
    validate_key(self.task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'Task 3' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-04-02T06:25:14.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:14.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2025-04-02T06:25:18.567+0000] {processor.py:186} INFO - Started process (PID=974) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:18.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:25:18.574+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:18.591+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:18.705+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.704+0000] {override.py:1930} INFO - Created Permission View: can read on DAG:ingest_test
[2025-04-02T06:25:18.710+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.709+0000] {override.py:1930} INFO - Created Permission View: can edit on DAG:ingest_test
[2025-04-02T06:25:18.712+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.712+0000] {override.py:1930} INFO - Created Permission View: can delete on DAG:ingest_test
[2025-04-02T06:25:18.715+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.715+0000] {override.py:1930} INFO - Created Permission View: can read on DAG Run:ingest_test
[2025-04-02T06:25:18.718+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.718+0000] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:ingest_test
[2025-04-02T06:25:18.720+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.720+0000] {override.py:1930} INFO - Created Permission View: can create on DAG Run:ingest_test
[2025-04-02T06:25:18.722+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.722+0000] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:ingest_test
[2025-04-02T06:25:18.723+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.723+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:25:18.740+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.739+0000] {dag.py:3262} INFO - Creating ORM DAG for ingest_test
[2025-04-02T06:25:18.742+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:18.742+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:25:18.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.217 seconds
[2025-04-02T06:25:48.896+0000] {processor.py:186} INFO - Started process (PID=1038) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:48.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:25:48.900+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:48.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:48.911+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:48.924+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:48.924+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:25:48.931+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:48.931+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:25:48.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2025-04-02T06:25:55.044+0000] {processor.py:186} INFO - Started process (PID=1075) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:55.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:25:55.047+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:55.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:55.060+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:25:55.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 4, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:25:55.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:25:55.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2025-04-02T06:26:02.140+0000] {processor.py:186} INFO - Started process (PID=1076) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:02.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:02.146+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:02.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:02.160+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:02.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 16
    def get_data
                ^
SyntaxError: expected '('
[2025-04-02T06:26:02.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:02.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2025-04-02T06:26:04.171+0000] {processor.py:186} INFO - Started process (PID=1083) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:04.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:04.174+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:04.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:04.177+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:04.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 19
    with DAG(
    ^^^^
IndentationError: expected an indented block after function definition on line 16
[2025-04-02T06:26:04.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:04.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2025-04-02T06:26:09.810+0000] {processor.py:186} INFO - Started process (PID=1098) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:09.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:09.814+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:09.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:09.820+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:09.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 19
    with DAG(
    ^^^^
IndentationError: expected an indented block after function definition on line 16
[2025-04-02T06:26:09.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:09.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2025-04-02T06:26:14.105+0000] {processor.py:186} INFO - Started process (PID=1106) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:14.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:14.108+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:14.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:14.116+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:14.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 19
    with DAG(
    ^^^^
IndentationError: expected an indented block after function definition on line 16
[2025-04-02T06:26:14.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:14.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2025-04-02T06:26:18.187+0000] {processor.py:186} INFO - Started process (PID=1107) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:18.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:18.190+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:18.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:18.194+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:18.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 4, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:26:18.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:18.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2025-04-02T06:26:31.514+0000] {processor.py:186} INFO - Started process (PID=1144) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:31.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:31.521+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:31.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:31.531+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:31.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 3
    from airflow.p
                  ^
SyntaxError: invalid syntax
[2025-04-02T06:26:31.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:31.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2025-04-02T06:26:37.595+0000] {processor.py:186} INFO - Started process (PID=1151) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:37.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:37.600+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:37.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:37.614+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:37.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:26:37.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:37.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2025-04-02T06:26:49.641+0000] {processor.py:186} INFO - Started process (PID=1173) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:49.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:49.643+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:49.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:49.648+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:49.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 41
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-04-02T06:26:49.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:49.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2025-04-02T06:26:52.761+0000] {processor.py:186} INFO - Started process (PID=1174) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:52.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:52.770+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:52.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:52.785+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:52.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:26:52.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:52.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2025-04-02T06:26:54.959+0000] {processor.py:186} INFO - Started process (PID=1179) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:54.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:54.962+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:54.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:54.978+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:54.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:26:54.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:55.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.141 seconds
[2025-04-02T06:26:56.506+0000] {processor.py:186} INFO - Started process (PID=1196) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:56.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:56.508+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:56.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:56.529+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:56.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:26:56.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:56.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2025-04-02T06:26:59.195+0000] {processor.py:186} INFO - Started process (PID=1213) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:59.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:26:59.201+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:59.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:59.208+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:26:59.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 40
    python_callable=
    ^^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-04-02T06:26:59.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:26:59.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2025-04-02T06:27:02.234+0000] {processor.py:186} INFO - Started process (PID=1214) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:02.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:27:02.236+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:02.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:02.242+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:02.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:27:02.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:02.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2025-04-02T06:27:08.421+0000] {processor.py:186} INFO - Started process (PID=1221) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:08.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:27:08.424+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:08.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:08.431+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:08.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:27:08.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:08.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2025-04-02T06:27:39.097+0000] {processor.py:186} INFO - Started process (PID=1285) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:39.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:27:39.101+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:39.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:39.113+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:39.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:27:39.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:39.142+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2025-04-02T06:27:46.055+0000] {processor.py:186} INFO - Started process (PID=1307) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:46.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:27:46.058+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:46.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:46.069+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:46.128+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:46.128+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:27:46.136+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:46.135+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:27:46.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.099 seconds
[2025-04-02T06:27:50.114+0000] {processor.py:186} INFO - Started process (PID=1308) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:50.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:27:50.117+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:50.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:50.126+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:50.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from .te import get_data
ImportError: attempted relative import with no known parent package
[2025-04-02T06:27:50.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:50.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2025-04-02T06:27:52.126+0000] {processor.py:186} INFO - Started process (PID=1309) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:52.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:27:52.128+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:52.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:52.131+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:52.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5
    from  import get_data
          ^^^^^^
SyntaxError: invalid syntax
[2025-04-02T06:27:52.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:52.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2025-04-02T06:27:54.181+0000] {processor.py:186} INFO - Started process (PID=1310) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:54.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:27:54.184+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:54.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:54.195+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:54.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from .. import get_data
ImportError: attempted relative import with no known parent package
[2025-04-02T06:27:54.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:54.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2025-04-02T06:27:58.495+0000] {processor.py:186} INFO - Started process (PID=1347) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:58.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:27:58.497+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:58.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:58.502+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:27:58.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from ..src.test_function import get_data
ImportError: attempted relative import with no known parent package
[2025-04-02T06:27:58.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:27:58.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.019 seconds
[2025-04-02T06:31:10.800+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:31:10.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:31:10.810+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:31:10.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:31:10.822+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:31:10.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from ..src.test_function import get_data
ImportError: attempted relative import with no known parent package
[2025-04-02T06:31:10.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:31:10.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2025-04-02T06:31:41.224+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:31:41.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:31:41.229+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:31:41.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:31:41.234+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:31:41.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from ..src.test_function import get_data
ImportError: attempted relative import with no known parent package
[2025-04-02T06:31:41.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:31:41.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2025-04-02T06:32:11.666+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:32:11.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:32:11.669+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:32:11.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:32:11.674+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:32:11.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from ..src.test_function import get_data
ImportError: attempted relative import with no known parent package
[2025-04-02T06:32:11.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:32:11.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2025-04-02T06:32:42.037+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:32:42.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:32:42.041+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:32:42.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:32:42.057+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:32:42.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from ..src.test_function import get_data
ImportError: attempted relative import with no known parent package
[2025-04-02T06:32:42.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:32:42.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.091 seconds
[2025-04-02T06:33:05.437+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:33:05.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:33:05.442+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:33:05.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:33:05.452+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:33:05.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:33:05.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:33:05.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.073 seconds
[2025-04-02T06:33:35.906+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:33:35.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:33:35.913+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:33:35.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:33:35.928+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:33:35.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:33:35.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:33:35.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.063 seconds
[2025-04-02T06:34:06.245+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:34:06.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:34:06.251+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:34:06.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:34:06.263+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:34:06.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:34:06.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:34:06.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2025-04-02T06:34:36.646+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:34:36.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:34:36.651+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:34:36.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:34:36.660+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:34:36.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:34:36.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:34:36.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2025-04-02T06:35:07.040+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:35:07.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:35:07.043+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:35:07.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:35:07.050+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:35:07.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:35:07.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:35:07.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2025-04-02T06:35:37.372+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:35:37.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:35:37.377+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:35:37.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:35:37.386+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:35:37.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:35:37.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:35:37.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2025-04-02T06:36:07.741+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:36:07.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:36:07.744+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:36:07.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:36:07.751+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:36:07.749+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:36:07.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:36:07.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2025-04-02T06:36:38.215+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:36:38.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:36:38.219+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:36:38.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:36:38.226+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:36:38.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:36:38.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:36:38.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2025-04-02T06:37:08.585+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:08.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:08.589+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:08.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:08.595+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:08.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:37:08.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:08.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2025-04-02T06:37:30.891+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:30.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:30.896+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:30.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:30.904+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:30.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5
    from src. import get_data
              ^^^^^^
SyntaxError: invalid syntax
[2025-04-02T06:37:30.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:30.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2025-04-02T06:37:33.930+0000] {processor.py:186} INFO - Started process (PID=141) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:33.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:33.934+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:33.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:33.938+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:33.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5
    from src. import get_data
              ^^^^^^
SyntaxError: invalid syntax
[2025-04-02T06:37:33.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:33.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2025-04-02T06:37:42.089+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:42.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:42.094+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:42.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:42.104+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:42.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function   import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:37:42.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:42.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2025-04-02T06:37:43.097+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:43.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:43.099+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:43.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:43.107+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:43.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function  import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:37:43.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:43.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2025-04-02T06:37:46.149+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:46.151+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:46.152+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:46.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:46.159+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:46.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:37:46.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:46.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2025-04-02T06:37:50.236+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:50.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:50.239+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:50.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:50.247+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:50.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:37:50.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:50.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2025-04-02T06:37:51.271+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:51.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:51.275+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:51.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:51.284+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:51.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:37:51.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:51.315+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2025-04-02T06:37:54.332+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:54.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:37:54.334+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:54.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:54.339+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:37:54.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:37:54.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:37:54.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2025-04-02T06:38:13.633+0000] {processor.py:186} INFO - Started process (PID=154) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:13.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:38:13.637+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:38:13.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:13.647+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:38:13.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:38:13.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:13.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2025-04-02T06:38:43.956+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:43.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:38:43.958+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:38:43.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:43.963+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:38:43.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:38:43.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:43.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2025-04-02T06:38:51.069+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:51.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:38:51.073+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:38:51.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:51.084+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:38:51.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:38:51.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:38:51.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2025-04-02T06:39:21.485+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:21.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:39:21.505+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:39:21.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:21.516+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:39:21.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.test.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:39:21.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:21.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.077 seconds
[2025-04-02T06:39:47.910+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:47.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:39:47.913+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:39:47.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:47.919+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:39:47.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5
    from test. import get_data
               ^^^^^^
SyntaxError: invalid syntax
[2025-04-02T06:39:47.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:47.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2025-04-02T06:39:49.963+0000] {processor.py:186} INFO - Started process (PID=183) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:49.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:39:49.965+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:39:49.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:49.975+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:39:49.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from test.g import get_data
ModuleNotFoundError: No module named 'test.g'
[2025-04-02T06:39:49.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:49.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2025-04-02T06:39:52.006+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:52.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:39:52.007+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:39:52.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:52.012+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:39:52.011+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from test.test import get_data
ModuleNotFoundError: No module named 'test.test'
[2025-04-02T06:39:52.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:39:52.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2025-04-02T06:40:00.150+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:00.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:40:00.162+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:00.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:00.181+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:00.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5
    from  import get_data
          ^^^^^^
SyntaxError: invalid syntax
[2025-04-02T06:40:00.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:00.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.072 seconds
[2025-04-02T06:40:30.560+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:30.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:40:30.565+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:30.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:30.572+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:30.571+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5
    from ut
           ^
SyntaxError: invalid syntax
[2025-04-02T06:40:30.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:30.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2025-04-02T06:40:32.602+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:32.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:40:32.605+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:32.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:32.610+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:32.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5
    from utils
              ^
SyntaxError: invalid syntax
[2025-04-02T06:40:32.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:32.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2025-04-02T06:40:46.785+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:46.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:40:46.788+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:46.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:46.793+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:46.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5
    from utils.
               ^
SyntaxError: invalid syntax
[2025-04-02T06:40:46.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:46.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2025-04-02T06:40:55.914+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:55.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:40:55.918+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:55.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:55.926+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:40:55.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:40:55.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:40:55.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2025-04-02T06:41:26.415+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:41:26.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:41:26.422+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:41:26.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:41:26.486+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:41:26.484+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:41:26.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:41:26.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.123 seconds
[2025-04-02T06:41:56.861+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:41:56.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:41:56.864+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:41:56.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:41:56.879+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:41:56.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:41:56.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:41:56.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2025-04-02T06:42:27.244+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:42:27.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:42:27.248+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:42:27.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:42:27.259+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:42:27.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:42:27.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:42:27.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2025-04-02T06:42:56.582+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:42:56.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:42:56.586+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:42:56.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:42:56.593+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:42:56.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:42:56.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:42:56.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2025-04-02T06:43:26.938+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:43:26.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:43:26.941+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:43:26.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:43:26.949+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:43:26.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:43:26.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:43:26.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2025-04-02T06:43:57.313+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:43:57.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:43:57.316+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:43:57.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:43:57.322+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:43:57.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:43:57.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:43:57.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2025-04-02T06:44:27.687+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:44:27.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:44:27.690+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:44:27.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:44:27.696+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:44:27.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:44:27.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:44:27.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2025-04-02T06:44:58.029+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:44:58.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:44:58.032+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:44:58.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:44:58.039+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:44:58.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:44:58.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:44:58.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2025-04-02T06:45:28.377+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:45:28.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:45:28.381+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:45:28.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:45:28.387+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:45:28.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:45:28.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:45:28.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2025-04-02T06:45:58.792+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:45:58.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:45:58.797+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:45:58.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:45:58.810+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:45:58.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:45:58.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:45:58.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2025-04-02T06:46:29.194+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:46:29.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:46:29.198+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:46:29.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:46:29.206+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:46:29.204+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:46:29.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:46:29.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2025-04-02T06:46:59.678+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:46:59.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:46:59.685+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:46:59.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:46:59.697+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:46:59.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:46:59.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:46:59.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.067 seconds
[2025-04-02T06:47:30.076+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:47:30.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:47:30.079+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:47:30.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:47:30.087+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:47:30.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:47:30.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:47:30.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2025-04-02T06:48:00.636+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:48:00.638+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:48:00.640+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:48:00.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:48:00.648+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:48:00.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:48:00.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:48:00.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2025-04-02T06:48:31.150+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:48:31.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:48:31.154+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:48:31.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:48:31.162+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:48:31.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:48:31.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:48:31.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2025-04-02T06:49:01.610+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:49:01.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:49:01.616+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:49:01.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:49:01.632+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:49:01.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:49:01.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:49:01.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2025-04-02T06:49:32.020+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:49:32.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:49:32.025+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:49:32.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:49:32.034+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:49:32.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:49:32.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:49:32.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2025-04-02T06:50:02.430+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:50:02.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:50:02.434+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:50:02.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:50:02.443+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:50:02.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:50:02.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:50:02.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2025-04-02T06:54:04.773+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:04.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:54:04.777+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:54:04.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:04.787+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:54:04.785+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:54:04.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:04.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.061 seconds
[2025-04-02T06:54:35.154+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:35.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:54:35.159+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:54:35.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:35.165+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:54:35.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from src.utils.test_function import get_data
ModuleNotFoundError: No module named 'src'
[2025-04-02T06:54:35.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:35.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2025-04-02T06:54:52.396+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:52.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:54:52.402+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:54:52.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:52.430+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:54:52.628+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:54:52.627+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:54:52.638+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:54:52.637+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:54:52.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.268 seconds
[2025-04-02T06:55:22.802+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:55:22.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:55:22.812+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:55:22.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:55:22.832+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:55:22.863+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:55:22.863+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:55:22.873+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:55:22.873+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:55:22.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.100 seconds
[2025-04-02T06:55:53.140+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:55:53.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:55:53.146+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:55:53.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:55:53.162+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:55:53.212+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:55:53.212+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:55:53.222+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:55:53.222+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:55:53.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.104 seconds
[2025-04-02T06:56:23.524+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:56:23.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:56:23.530+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:56:23.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:56:23.545+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:56:23.761+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:56:23.761+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:56:23.788+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:56:23.787+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:56:23.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.311 seconds
[2025-04-02T06:56:54.216+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:56:54.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:56:54.244+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:56:54.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:56:54.266+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:56:54.317+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:56:54.317+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:56:54.329+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:56:54.328+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:56:54.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.148 seconds
[2025-04-02T06:57:24.534+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:57:24.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:57:24.542+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:57:24.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:57:24.560+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:57:24.618+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:57:24.618+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:57:24.636+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:57:24.636+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:57:24.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.122 seconds
[2025-04-02T06:57:55.080+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:57:55.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:57:55.087+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:57:55.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:57:55.104+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:57:55.167+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:57:55.167+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:57:55.178+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:57:55.178+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:57:55.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.117 seconds
[2025-04-02T06:58:25.434+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:58:25.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:58:25.444+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:58:25.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:58:25.465+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:58:25.540+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:58:25.539+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:58:25.549+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:58:25.549+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:58:25.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.135 seconds
[2025-04-02T06:58:55.836+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:58:55.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:58:55.842+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:58:55.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:58:55.863+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:58:55.906+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:58:55.906+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:58:55.917+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:58:55.917+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:58:55.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.114 seconds
[2025-04-02T06:59:26.219+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:59:26.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:59:26.223+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:59:26.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:59:26.237+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:59:26.283+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:59:26.283+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:59:26.293+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:59:26.293+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:59:26.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.092 seconds
[2025-04-02T06:59:56.691+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T06:59:56.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T06:59:56.698+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:59:56.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T06:59:56.714+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T06:59:56.769+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:59:56.769+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T06:59:56.780+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:59:56.780+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T06:59:56.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.109 seconds
[2025-04-02T07:00:27.005+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:00:27.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:00:27.011+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:00:27.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:00:27.025+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:00:27.075+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:00:27.074+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:00:27.085+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:00:27.085+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:00:27.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.097 seconds
[2025-04-02T07:00:57.408+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:00:57.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:00:57.415+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:00:57.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:00:57.431+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:00:57.481+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:00:57.481+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:00:57.491+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:00:57.491+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:00:57.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.103 seconds
[2025-04-02T07:01:27.784+0000] {processor.py:186} INFO - Started process (PID=154) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:01:27.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:01:27.801+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:01:27.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:01:27.836+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:01:27.907+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:01:27.907+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:01:27.919+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:01:27.919+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:01:27.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.169 seconds
[2025-04-02T07:01:58.174+0000] {processor.py:186} INFO - Started process (PID=161) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:01:58.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:01:58.181+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:01:58.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:01:58.218+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:01:58.283+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:01:58.283+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:01:58.294+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:01:58.294+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:01:58.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.142 seconds
[2025-04-02T07:02:28.601+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:02:28.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:02:28.610+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:02:28.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:02:28.635+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:02:28.701+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:02:28.701+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:02:28.712+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:02:28.712+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:02:28.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.135 seconds
[2025-04-02T07:02:58.915+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:02:58.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:02:58.921+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:02:58.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:02:58.956+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:02:59.008+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:02:59.008+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:02:59.018+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:02:59.018+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:02:59.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.125 seconds
[2025-04-02T07:03:29.332+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:03:29.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:03:29.338+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:03:29.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:03:29.355+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:03:29.426+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:03:29.426+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:03:29.437+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:03:29.437+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:03:29.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.124 seconds
[2025-04-02T07:03:59.730+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:03:59.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:03:59.736+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:03:59.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:03:59.750+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:03:59.828+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:03:59.827+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:03:59.839+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:03:59.839+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:03:59.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.126 seconds
[2025-04-02T07:04:30.182+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:04:30.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:04:30.195+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:04:30.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:04:30.221+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:04:30.273+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:04:30.273+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:04:30.284+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:04:30.284+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:04:30.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.130 seconds
[2025-04-02T07:05:00.537+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:05:00.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:05:00.542+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:05:00.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:05:00.557+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:05:00.600+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:05:00.600+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:05:00.609+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:05:00.609+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:05:00.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.088 seconds
[2025-04-02T07:05:30.968+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:05:30.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:05:30.974+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:05:30.973+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:05:31.015+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:05:31.042+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:05:31.042+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:05:31.054+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:05:31.054+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:05:31.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.105 seconds
[2025-04-02T07:06:01.355+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:06:01.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:06:01.360+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:06:01.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:06:01.396+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:06:01.418+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:06:01.417+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:06:01.428+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:06:01.428+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:06:01.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.092 seconds
[2025-04-02T07:06:31.706+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:06:31.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:06:31.711+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:06:31.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:06:31.759+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:06:31.799+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:06:31.799+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:06:31.811+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:06:31.811+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:06:31.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.136 seconds
[2025-04-02T07:07:02.051+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:07:02.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:07:02.057+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:07:02.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:07:02.096+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:07:02.121+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:07:02.120+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:07:02.131+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:07:02.131+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:07:02.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.106 seconds
[2025-04-02T07:07:32.475+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:07:32.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:07:32.478+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:07:32.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:07:32.489+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:07:32.507+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:07:32.507+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:07:32.516+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:07:32.516+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:07:32.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.056 seconds
[2025-04-02T07:08:02.757+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:08:02.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:08:02.762+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:08:02.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:08:02.786+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:08:02.813+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:08:02.813+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:08:02.828+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:08:02.828+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:08:02.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.099 seconds
[2025-04-02T07:08:33.088+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:08:33.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:08:33.095+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:08:33.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:08:33.110+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:08:33.134+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:08:33.134+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:08:33.144+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:08:33.144+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:08:33.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.081 seconds
[2025-04-02T07:09:03.440+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:09:03.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:09:03.446+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:09:03.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:09:03.460+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:09:03.487+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:09:03.487+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:09:03.498+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:09:03.498+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:09:03.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.088 seconds
[2025-04-02T07:09:33.936+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:09:33.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:09:33.940+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:09:33.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:09:33.952+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:09:33.978+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:09:33.978+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:09:33.989+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:09:33.989+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:09:34.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.078 seconds
[2025-04-02T07:10:04.342+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:10:04.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:10:04.347+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:10:04.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:10:04.363+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:10:04.411+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:10:04.411+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:10:04.424+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:10:04.424+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:10:04.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.103 seconds
[2025-04-02T07:10:34.779+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:10:34.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:10:34.786+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:10:34.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:10:34.803+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:10:34.833+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:10:34.833+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:10:34.847+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:10:34.846+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:10:34.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.091 seconds
[2025-04-02T07:11:05.101+0000] {processor.py:186} INFO - Started process (PID=287) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:11:05.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:11:05.107+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:11:05.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:11:05.125+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:11:05.156+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:11:05.156+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:11:05.168+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:11:05.168+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:11:05.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.091 seconds
[2025-04-02T07:11:35.424+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:11:35.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:11:35.435+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:11:35.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:11:35.465+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:11:35.509+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:11:35.508+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:11:35.521+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:11:35.521+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:11:35.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.126 seconds
[2025-04-02T07:12:05.717+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:12:05.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:12:05.724+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:12:05.723+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:12:05.744+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:12:05.777+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:12:05.777+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:12:05.788+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:12:05.788+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:12:05.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.092 seconds
[2025-04-02T07:12:36.085+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:12:36.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:12:36.091+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:12:36.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:12:36.112+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:12:36.147+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:12:36.147+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:12:36.160+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:12:36.159+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:12:36.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.098 seconds
[2025-04-02T07:13:06.462+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:13:06.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:13:06.474+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:13:06.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:13:06.491+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:13:06.524+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:13:06.524+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:13:06.537+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:13:06.537+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:13:06.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.114 seconds
[2025-04-02T07:13:36.815+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:13:36.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:13:36.823+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:13:36.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:13:36.845+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:13:36.872+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:13:36.872+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:13:36.884+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:13:36.884+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:13:36.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.096 seconds
[2025-04-02T07:14:07.281+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:14:07.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:14:07.297+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:14:07.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:14:07.315+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:14:07.354+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:14:07.354+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:14:07.368+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:14:07.368+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:14:07.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.114 seconds
[2025-04-02T07:14:37.700+0000] {processor.py:186} INFO - Started process (PID=337) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:14:37.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:14:37.706+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:14:37.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:14:37.721+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:14:37.745+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:14:37.745+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:14:37.757+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:14:37.756+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:14:37.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.076 seconds
[2025-04-02T07:15:08.091+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:15:08.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:15:08.101+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:15:08.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:15:08.127+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:15:08.155+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:15:08.155+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:15:08.167+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:15:08.167+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:15:08.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.106 seconds
[2025-04-02T07:15:38.380+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:15:38.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:15:38.389+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:15:38.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:15:38.410+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:15:38.436+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:15:38.436+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:15:38.445+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:15:38.445+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:15:38.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.090 seconds
[2025-04-02T07:16:08.863+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:16:08.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:16:08.868+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:16:08.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:16:08.879+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:16:08.900+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:16:08.900+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:16:08.910+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:16:08.910+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:16:08.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2025-04-02T07:16:39.206+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:16:39.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:16:39.210+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:16:39.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:16:39.221+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:16:39.241+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:16:39.240+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:16:39.249+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:16:39.249+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:16:39.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.059 seconds
[2025-04-02T07:17:09.547+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:17:09.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:17:09.554+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:17:09.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:17:09.566+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:17:09.588+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:17:09.588+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:17:09.598+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:17:09.598+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:17:09.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.072 seconds
[2025-04-02T07:17:39.909+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:17:39.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:17:39.915+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:17:39.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:17:39.927+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:17:39.952+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:17:39.952+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:17:39.962+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:17:39.962+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:17:39.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.068 seconds
[2025-04-02T07:18:10.316+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:18:10.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:18:10.322+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:18:10.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:18:10.337+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:18:10.365+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:18:10.364+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:18:10.383+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:18:10.383+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:18:10.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2025-04-02T07:18:40.719+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/test_dag.py
[2025-04-02T07:18:40.730+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2025-04-02T07:18:40.747+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:18:40.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2025-04-02T07:18:40.767+0000] {processor.py:925} INFO - DAG(s) 'ingest_test' retrieved from /opt/airflow/dags/test_dag.py
[2025-04-02T07:18:40.809+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:18:40.808+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-02T07:18:40.823+0000] {logging_mixin.py:190} INFO - [2025-04-02T07:18:40.823+0000] {dag.py:4180} INFO - Setting next_dagrun for ingest_test to None, run_after=None
[2025-04-02T07:18:40.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag.py took 0.159 seconds
